name: airplane_entertainment_system
description: Airplane Entertainment System project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  aes_ui:
    path: packages/aes_ui
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  collection: ^1.18.0
  equatable: ^2.0.5
  flight_api_client:
    path: packages/flight_api_client
  flight_information_repository:
    path: packages/flight_information_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.2
  intl: ^0.19.0
  music_repository:
    path: packages/music_repository
  weather_api_client:
    path: packages/weather_api_client
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/weather/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
