name: airplane_entertainment_system
description: Airplane Entertainment System project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  aes_ui:
    path: packages/aes_ui
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  just_audio: ^0.9.39
  music_repository:
    path: packages/music_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
