name: airplane_entertainment_system
description: Airplane Entertainment System project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.11.0
  flutter: 3.41.2

workspace:
  - packages/aes_ui
  - packages/flight_api_client
  - packages/flight_information_repository
  - packages/music_repository
  - packages/music_visualizer_generator
  - packages/weather_api_client
  - packages/weather_repository

dependencies:
  aes_ui:
    path: packages/aes_ui
  audioplayers: ^6.5.1
  bloc: ^9.2.0
  collection: ^1.19.1
  equatable: ^2.0.8
  flight_api_client:
    path: packages/flight_api_client
  flight_information_repository:
    path: packages/flight_information_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.1.0
  intl: ^0.20.2
  music_repository:
    path: packages/music_repository
  weather_api_client:
    path: packages/weather_api_client
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.13.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.2.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/weather/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
