name: weather_repository
description: A repository for the weather information.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
  
dependencies:
  equatable: ^2.0.5
  rxdart: ^0.28.0
  weather_api_client:
    path: ../weather_api_client
