name: weather_repository
description: Provides (fake) real time information of the weather.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
  
dependencies:
  equatable: ^2.0.5
  meta: ^1.12.0
