name: flight_api_client
description: The flight API client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
